services:
  test: &defaults
    build:
      context: .
      target: base
    working_dir: /app
    command: go test ./...
    volumes:
      - .:/app
  app:
    <<: *defaults
    command: sh
    volumes:
      - .:/app
  ci:
    <<: *defaults
    build:
      context: .
      target: ci
    volumes: []
  morse:
    <<: *defaults
    working_dir: /
    command: []
    build:
      context: .
    volumes: []
